name: chit_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.0
  date_time: ^0.11.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/chat_app_logo.png
